language: java
dist: trusty
sudo: required
jdk:
  - openjdk11
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
addons:
  sonarcloud:
    organization: "rfernandon-github"
    token: "${SONAR_TOKEN}"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
  provider: script
  script: mvn clean deploy -Dmaven.test.skip=true
  skip_cleanup: true
  on:
    branch: master
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
