language: java
dist: trusty
sudo: required
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "rfernandon-github"
    token: "${SONAR_TOKEN}"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean deploy
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
